version: "3.7"

services:
  angular-app:
    container_name: marvel-heroes
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - ".:/app"
    ports:
      - "4200:4200"
      
    command: >
      bash -c "npm run start"